
export enum TransactionType {
  INCOME = 'INCOME',
  EXPENSE = 'EXPENSE'
}

export enum AccountType {
  CASH = 'CASH',
  BANK = 'BANK',
  ESEWA = 'ESEWA',
  KHALTI = 'KHALTI'
}

export interface Transaction {
  id: string;
  amount: number;
  category: string;
  type: TransactionType;
  account: AccountType;
  description: string;
  adDate: Date;
  bsDate: string;
  isAutoGenerated?: boolean;
}

export interface AppNotification {
  id: string;
  type: 'BUDGET_EXCEEDED' | 'BUDGET_WARNING' | 'GOAL_REACHED' | 'INFO';
  title: string;
  message: string;
  dateBS: string;
  isRead: boolean;
  categoryIcon?: string;
  categoryColor?: string;
}

export interface LinkedAccount {
  id: string;
  provider: string;
  type: 'BANK' | 'WALLET';
  isActive: boolean;
  lastSynced: string;
}

export interface Category {
  id: string;
  name: string;
  icon: string;
  color: string;
  type: TransactionType;
  isDefault?: boolean;
}

export interface Budget {
  id: string;
  categoryId: string;
  amount: number;
  month: number;
  year: number;
}

export interface FinancialGoal {
  id: string;
  name: string;
  targetAmount: number;
  currentAmount: number;
  targetDateBS: string;
  icon: string;
  color: string;
}

export interface AccountBalances {
  cash: number;
  bank: number;
  esewa: number;
  khalti: number;
}

export enum DashboardWidget {
  SUMMARY_CARDS = 'SUMMARY_CARDS',
  BUDGET_PROGRESS = 'BUDGET_PROGRESS',
  GOALS_SUMMARY = 'GOALS_SUMMARY',
  INCOME_COMPARISON = 'INCOME_COMPARISON'
}

export interface WidgetConfig {
  id: DashboardWidget;
  visible: boolean;
  label: string;
}

export interface UserProfile {
  name: string;
  motto: string;
  avatar: string;
  color: string;
}
