
import React, { useState } from 'react';
import { LinkedAccount, Transaction, AccountType, TransactionType } from '../types';
import { parseTransactionNotification } from '../services/geminiService';
import { getCurrentBSDate } from '../utils/bsCalendar';

interface SyncManagerProps {
  linkedAccounts: LinkedAccount[];
  onLink: (account: LinkedAccount) => void;
  onUnlink: (id: string) => void;
  onAddTransaction: (t: Transaction) => void;
  onClose: () => void;
}

const PROVIDERS = [
  { name: 'eSewa', type: 'WALLET', icon: 'fa-wallet', color: 'bg-green-600' },
  { name: 'Khalti', type: 'WALLET', icon: 'fa-wallet', color: 'bg-purple-700' },
  { name: 'Nabil Bank', type: 'BANK', icon: 'fa-building-columns', color: 'bg-red-700' },
  { name: 'Global IME', type: 'BANK', icon: 'fa-building-columns', color: 'bg-blue-800' },
];

const SyncManager: React.FC<SyncManagerProps> = ({ linkedAccounts, onLink, onUnlink, onAddTransaction, onClose }) => {
  const [isLinking, setIsLinking] = useState(false);
  const [notificationText, setNotificationText] = useState('');
  const [isParsing, setIsParsing] = useState(false);
  const [parsedResult, setParsedResult] = useState<Partial<Transaction> | null>(null);

  const handleLink = (provider: typeof PROVIDERS[0]) => {
    const newAccount: LinkedAccount = {
      id: crypto.randomUUID(),
      provider: provider.name,
      type: provider.type as 'BANK' | 'WALLET',
      isActive: true,
      lastSynced: getCurrentBSDate()
    };
    onLink(newAccount);
    setIsLinking(false);
  };

  const handleParse = async () => {
    if (!notificationText.trim()) return;
    setIsParsing(true);
    setParsedResult(null);
    
    const [year] = getCurrentBSDate().split('-').map(Number);
    const result = await parseTransactionNotification(notificationText, year);
    
    if (result) {
      setParsedResult(result);
    } else {
      alert("Could not recognize transaction details. Please check the text.");
    }
    setIsParsing(false);
  };

  const confirmTransaction = () => {
    if (parsedResult) {
      const fullTransaction: Transaction = {
        id: crypto.randomUUID(),
        amount: parsedResult.amount || 0,
        category: parsedResult.category || 'other',
        type: parsedResult.type as TransactionType || TransactionType.EXPENSE,
        account: parsedResult.account as AccountType || AccountType.BANK,
        description: parsedResult.description || 'Auto-synced transaction',
        bsDate: parsedResult.bsDate || getCurrentBSDate(),
        adDate: parsedResult.adDate || new Date(),
        isAutoGenerated: true
      };
      onAddTransaction(fullTransaction);
      setParsedResult(null);
      setNotificationText('');
    }
  };

  return (
    <div className="fixed inset-0 bg-black/60 backdrop-blur-md z-[110] flex items-center justify-center p-4">
      <div className="bg-white w-full max-w-2xl rounded-[2.5rem] shadow-2xl overflow-hidden flex flex-col max-h-[90vh] animate-in fade-in zoom-in duration-300">
        <div className="p-8 border-b border-slate-100 flex justify-between items-center bg-white sticky top-0 z-10">
          <div>
            <h2 className="text-2xl font-black text-slate-800 tracking-tight">Sync Hub</h2>
            <p className="text-[10px] font-bold text-slate-400 uppercase tracking-widest mt-1">Automate your tracking with AI</p>
          </div>
          <button onClick={onClose} className="h-12 w-12 flex items-center justify-center rounded-full bg-slate-50 text-slate-400 hover:text-slate-600 transition-colors">
            <i className="fa-solid fa-xmark text-xl"></i>
          </button>
        </div>

        <div className="flex-1 overflow-y-auto p-8 space-y-10">
          {/* Automation Section */}
          <section className="space-y-4">
            <div className="flex items-center gap-3">
              <div className="h-8 w-8 bg-indigo-600 rounded-lg flex items-center justify-center text-white text-xs shadow-md">
                <i className="fa-solid fa-wand-magic-sparkles"></i>
              </div>
              <h3 className="font-black text-slate-700 uppercase tracking-tight">Quick Sync Parser</h3>
            </div>
            <div className="bg-slate-50 p-6 rounded-3xl border border-slate-100 space-y-4">
              <p className="text-xs text-slate-500 font-medium">Paste a bank SMS, email notification, or transaction text below. Our AI will handle the rest.</p>
              <textarea
                value={notificationText}
                onChange={(e) => setNotificationText(e.target.value)}
                placeholder="Example: Rs. 1200 paid to Foodmandu from Nabil Bank on 2081-05-12"
                className="w-full h-32 p-4 bg-white border border-slate-200 rounded-2xl focus:ring-2 focus:ring-indigo-600 outline-none text-sm font-medium resize-none transition-all"
              />
              <button
                onClick={handleParse}
                disabled={isParsing || !notificationText.trim()}
                className="w-full py-4 bg-indigo-600 text-white rounded-2xl font-black text-sm uppercase tracking-widest shadow-lg shadow-indigo-100 hover:bg-indigo-700 disabled:opacity-50 transition-all active:scale-[0.98]"
              >
                {isParsing ? <i className="fa-solid fa-circle-notch fa-spin mr-2"></i> : <i className="fa-solid fa-bolt mr-2"></i>}
                {isParsing ? 'Analyzing Notification...' : 'Extract Transaction'}
              </button>

              {parsedResult && (
                <div className="mt-4 p-5 bg-white border-2 border-indigo-100 rounded-2xl animate-in slide-in-from-top-4 duration-300">
                  <div className="flex justify-between items-start mb-4">
                    <h4 className="text-xs font-black text-indigo-600 uppercase tracking-widest">Detected Transaction</h4>
                    <button onClick={() => setParsedResult(null)} className="text-slate-300 hover:text-slate-500"><i className="fa-solid fa-xmark"></i></button>
                  </div>
                  <div className="grid grid-cols-2 gap-4 mb-6">
                    <div>
                      <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Amount</p>
                      <p className="font-black text-slate-800">Rs. {parsedResult.amount?.toLocaleString()}</p>
                    </div>
                    <div>
                      <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Date (BS)</p>
                      <p className="font-black text-slate-800">{parsedResult.bsDate}</p>
                    </div>
                    <div>
                      <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Type</p>
                      <p className={`font-black uppercase text-[10px] ${parsedResult.type === 'INCOME' ? 'text-emerald-600' : 'text-rose-600'}`}>
                        {parsedResult.type}
                      </p>
                    </div>
                    <div>
                      <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Account</p>
                      <p className="font-black text-slate-800 uppercase text-[10px]">{parsedResult.account}</p>
                    </div>
                  </div>
                  <button
                    onClick={confirmTransaction}
                    className="w-full py-3 bg-emerald-600 text-white rounded-xl font-black text-xs uppercase tracking-widest hover:bg-emerald-700 transition-all"
                  >
                    Confirm & Save Entry
                  </button>
                </div>
              )}
            </div>
          </section>

          {/* Linked Accounts Section */}
          <section className="space-y-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-3">
                <div className="h-8 w-8 bg-slate-800 rounded-lg flex items-center justify-center text-white text-xs shadow-md">
                  <i className="fa-solid fa-link"></i>
                </div>
                <h3 className="font-black text-slate-700 uppercase tracking-tight">Linked Sources</h3>
              </div>
              <button 
                onClick={() => setIsLinking(true)}
                className="text-xs font-black text-indigo-600 bg-indigo-50 px-4 py-2 rounded-full hover:bg-indigo-100 transition-colors"
              >
                + Link New
              </button>
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-4">
              {linkedAccounts.length > 0 ? (
                linkedAccounts.map(acc => (
                  <div key={acc.id} className="p-5 bg-white border border-slate-100 rounded-[2rem] shadow-sm flex items-center justify-between group">
                    <div className="flex items-center gap-4">
                      <div className={`h-12 w-12 rounded-2xl flex items-center justify-center text-white shadow-md ${PROVIDERS.find(p => p.name === acc.provider)?.color || 'bg-slate-400'}`}>
                        <i className={`fa-solid ${PROVIDERS.find(p => p.name === acc.provider)?.icon || 'fa-university'}`}></i>
                      </div>
                      <div>
                        <p className="font-black text-slate-800 text-sm">{acc.provider}</p>
                        <p className="text-[9px] font-bold text-slate-400 uppercase tracking-widest">Last Synced: {acc.lastSynced}</p>
                      </div>
                    </div>
                    <button 
                      onClick={() => onUnlink(acc.id)}
                      className="h-8 w-8 flex items-center justify-center text-slate-300 hover:text-rose-500 transition-colors opacity-0 group-hover:opacity-100"
                    >
                      <i className="fa-solid fa-unlink"></i>
                    </button>
                  </div>
                ))
              ) : (
                <div className="col-span-full py-10 text-center border-2 border-dashed border-slate-100 rounded-[2rem]">
                  <p className="text-slate-400 font-bold text-sm">No linked accounts yet.</p>
                </div>
              )}
            </div>
          </section>
        </div>
      </div>

      {isLinking && (
        <div className="fixed inset-0 bg-black/40 backdrop-blur-sm z-[120] flex items-center justify-center p-4">
          <div className="bg-white w-full max-w-sm rounded-[2.5rem] shadow-2xl overflow-hidden animate-in zoom-in duration-200">
            <div className="p-6 border-b border-slate-100 flex justify-between items-center">
              <h3 className="font-black text-slate-800 uppercase tracking-widest text-sm">Select Provider</h3>
              <button onClick={() => setIsLinking(false)} className="text-slate-400"><i className="fa-solid fa-xmark"></i></button>
            </div>
            <div className="p-4 grid grid-cols-1 gap-2">
              {PROVIDERS.map(p => (
                <button
                  key={p.name}
                  onClick={() => handleLink(p)}
                  className="flex items-center gap-4 p-4 rounded-2xl hover:bg-slate-50 transition-all text-left group"
                >
                  <div className={`h-10 w-10 rounded-xl flex items-center justify-center text-white shadow-sm ${p.color}`}>
                    <i className={`fa-solid ${p.icon}`}></i>
                  </div>
                  <div>
                    <p className="font-bold text-slate-800 text-sm">{p.name}</p>
                    <p className="text-[10px] text-slate-400 font-bold uppercase tracking-wider">{p.type}</p>
                  </div>
                  <i className="fa-solid fa-chevron-right ml-auto text-slate-200 group-hover:text-indigo-600 transition-colors"></i>
                </button>
              ))}
            </div>
          </div>
        </div>
      )}
    </div>
  );
};

export default SyncManager;
